#!/bin/bash
echo "Confirm flash? $1"
echo "(Press ENTER to confirm, CTRL-C to exit.)"
read

echo "On the ESP8266 board:
echo "  Hold down GPIO0 and RESET."
echo "  Then release RESET."
echo "  Then release GPIO0."
echo "Once you have done these steps, press ENTER."
read

sudo python ../esptool.py -p /dev/ttyUSB0 write_flash 0x00 $1
